// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/current-event-with-tag-detail": {
            "get": {
                "description": "当前获取活动与Tag和详情",
                "tags": [
                    "活动"
                ],
                "summary": "当前活动和活动与Tag和详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/current-pool-with-tag": {
            "get": {
                "description": "获取当前卡池信息和标签",
                "tags": [
                    "卡池"
                ],
                "summary": "获取当前卡池信息和标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "versionId",
                        "name": "versionId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "time",
                        "name": "time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/current-version-event-with-tag": {
            "get": {
                "description": "获取当前版本活动和tag",
                "tags": [
                    "版本活动"
                ],
                "summary": "获取当前版本活动和tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "version_num",
                        "name": "version_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/current-version-with-tag": {
            "get": {
                "description": "当前获取版本与Tag",
                "tags": [
                    "版本"
                ],
                "summary": "当前版本和版本与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "time",
                        "name": "time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/daily": {
            "get": {
                "description": "获取用户每日任务",
                "tags": [
                    "每日任务"
                ],
                "summary": "每日任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "刷新用户每日任务",
                "tags": [
                    "每日任务"
                ],
                "summary": "刷新每日任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event": {
            "get": {
                "description": "获取活动列表",
                "tags": [
                    "活动"
                ],
                "summary": "活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "更新活动信息",
                "tags": [
                    "活动"
                ],
                "summary": "更新活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "primogems",
                        "name": "primogems",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "award",
                        "name": "award",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "preTask",
                        "name": "preTask",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "coPlay",
                        "name": "coPlay",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增活动信息",
                "tags": [
                    "活动"
                ],
                "summary": "新增活动信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "primogems",
                        "name": "primogems",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "award",
                        "name": "award",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "preTask",
                        "name": "preTask",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "coPlay",
                        "name": "coPlay",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event-delete": {
            "post": {
                "description": "删除活动",
                "tags": [
                    "活动"
                ],
                "summary": "删除活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event-tag": {
            "get": {
                "description": "获取Tag",
                "tags": [
                    "活动"
                ],
                "summary": "活动Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event-with-tag": {
            "get": {
                "description": "获取活动与Tag",
                "tags": [
                    "活动"
                ],
                "summary": "活动和活动与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建活动与Tag",
                "tags": [
                    "活动"
                ],
                "summary": "创建活动与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "EventId",
                        "name": "eventId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event-with-tag-delete": {
            "post": {
                "description": "删除活动与Tag",
                "tags": [
                    "活动"
                ],
                "summary": "删除活动和活动与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "eventId",
                        "name": "eventId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event-with-tag-detail": {
            "get": {
                "description": "获取活动与Tag和详情",
                "tags": [
                    "活动"
                ],
                "summary": "活动和活动与Tag和详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "time",
                        "name": "time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/eventDetail": {
            "get": {
                "description": "获取活动细节信息",
                "tags": [
                    "活动细节"
                ],
                "summary": "获取活动细节信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "获取活动细节信息",
                "tags": [
                    "活动细节"
                ],
                "summary": "更新活动细节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增活动细节信息",
                "tags": [
                    "活动细节"
                ],
                "summary": "新增活动细节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "versionNum",
                        "name": "versionNum",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Img",
                        "name": "Img",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Star",
                        "name": "Star",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "Type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "StartTime",
                        "name": "StartTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "EndTime",
                        "name": "EndTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/eventDetail-delete": {
            "post": {
                "description": "删除活动细节",
                "tags": [
                    "活动细节"
                ],
                "summary": "删除活动细节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "登录",
                "tags": [
                    "用户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "ping",
                "tags": [
                    "测试"
                ],
                "summary": "ping",
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"data\":\"pong\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pool": {
            "get": {
                "description": "获取卡池信息",
                "tags": [
                    "卡池"
                ],
                "summary": "获取卡池信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "获取卡池信息",
                "tags": [
                    "卡池"
                ],
                "summary": "更新卡池",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增卡池信息",
                "tags": [
                    "卡池"
                ],
                "summary": "新增卡池",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "versionNum",
                        "name": "versionNum",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Img",
                        "name": "Img",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Star",
                        "name": "Star",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "Type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "StartTime",
                        "name": "StartTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "EndTime",
                        "name": "EndTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pool-delete": {
            "post": {
                "description": "删除卡池",
                "tags": [
                    "卡池"
                ],
                "summary": "删除卡池",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pool-tag": {
            "get": {
                "description": "获取Tag",
                "tags": [
                    "卡池"
                ],
                "summary": "活动Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pool-with-tag": {
            "get": {
                "description": "获取卡池信息和标签",
                "tags": [
                    "卡池"
                ],
                "summary": "获取卡池信息和标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建Tag",
                "tags": [
                    "卡池"
                ],
                "summary": "创建Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "EventId",
                        "name": "eventId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pool-with-tag-delete": {
            "post": {
                "description": "删除Tag",
                "tags": [
                    "卡池"
                ],
                "summary": "删除活Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "eventId",
                        "name": "eventId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "注册",
                "tags": [
                    "用户"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tag": {
            "get": {
                "description": "获取标签列表",
                "tags": [
                    "标签"
                ],
                "summary": "标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分类",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "更新标签信息",
                "tags": [
                    "标签"
                ],
                "summary": "更新标签信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "primogems",
                        "name": "primogems",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "award",
                        "name": "award",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "preTask",
                        "name": "preTask",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "coPlay",
                        "name": "coPlay",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增标签信息",
                "tags": [
                    "标签"
                ],
                "summary": "新增标签信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "primogems",
                        "name": "primogems",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "award",
                        "name": "award",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "preTask",
                        "name": "preTask",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "coPlay",
                        "name": "coPlay",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tag-delete": {
            "post": {
                "description": "删除标签",
                "tags": [
                    "标签"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "获取用户列表",
                "tags": [
                    "用户"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "修改用户信息",
                "tags": [
                    "用户"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "role",
                        "name": "role",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增用户信息",
                "tags": [
                    "用户"
                ],
                "summary": "新增用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "role",
                        "name": "role",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-delete": {
            "post": {
                "description": "删除用户",
                "tags": [
                    "用户"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-event": {
            "get": {
                "description": "查询用户活动信息",
                "tags": [
                    "用户活动"
                ],
                "summary": "查询用户活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "eventId",
                        "name": "eventId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "更新用户活动信息",
                "tags": [
                    "用户活动"
                ],
                "summary": "更新用户活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建用户活动信息",
                "tags": [
                    "用户活动"
                ],
                "summary": "创建用户活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "eventId",
                        "name": "eventId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-event-delete": {
            "post": {
                "description": "删除用户活动信息",
                "tags": [
                    "用户活动"
                ],
                "summary": "删除用户活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-password": {
            "post": {
                "description": "修改密码",
                "tags": [
                    "用户"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "oldPassword",
                        "name": "oldPassword",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "oldPassword",
                        "name": "newPassword",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-private": {
            "get": {
                "description": "查询用户自定义活动信息",
                "tags": [
                    "用户自定义活动"
                ],
                "summary": "查询用户自定义活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "更新用户自定义活动信息",
                "tags": [
                    "用户自定义活动"
                ],
                "summary": "更新用户自定义活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todo",
                        "name": "todo",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "autoUpdate",
                        "name": "autoUpdate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "updateHour",
                        "name": "updateHour",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建用户自定义活动信息",
                "tags": [
                    "用户自定义活动"
                ],
                "summary": "创建用户自定义活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todo",
                        "name": "todo",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "autoUpdate",
                        "name": "autoUpdate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "updateHour",
                        "name": "updateHour",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-private-delete": {
            "post": {
                "description": "删除用户自定义活动信息",
                "tags": [
                    "用户自定义活动"
                ],
                "summary": "删除用户自定义活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-token": {
            "post": {
                "description": "更新Token",
                "tags": [
                    "用户"
                ],
                "summary": "更新Token",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "oldPassword",
                        "name": "token",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-version-event": {
            "get": {
                "description": "查询用户版本活动信息",
                "tags": [
                    "用户版本活动"
                ],
                "summary": "查询用户版本活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "versionEventId",
                        "name": "versionEventId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "更新用户版本活动信息",
                "tags": [
                    "用户版本活动"
                ],
                "summary": "更新用户版本活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建用户版本活动信息",
                "tags": [
                    "用户版本活动"
                ],
                "summary": "创建用户版本活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "versionEventId",
                        "name": "versionEventId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-version-event-delete": {
            "post": {
                "description": "删除用户版本活动信息",
                "tags": [
                    "用户版本活动"
                ],
                "summary": "删除用户版本活动信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "获取版本列表",
                "tags": [
                    "版本"
                ],
                "summary": "版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "更新版本信息",
                "tags": [
                    "版本"
                ],
                "summary": "更新版本信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "num",
                        "name": "num",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Img",
                        "name": "img",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增版本信息",
                "tags": [
                    "版本"
                ],
                "summary": "新增版本信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "num",
                        "name": "num",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Img",
                        "name": "img",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-delete": {
            "post": {
                "description": "删除版本",
                "tags": [
                    "版本"
                ],
                "summary": "删除版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-event": {
            "get": {
                "description": "获取版本活动",
                "tags": [
                    "版本活动"
                ],
                "summary": "根据版本获取版本活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "version_num",
                        "name": "version_num",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "修改版本活动",
                "tags": [
                    "版本活动"
                ],
                "summary": "修改版本活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "versionNum",
                        "name": "versionNum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "content",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "level",
                        "name": "level",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增活动",
                "tags": [
                    "版本活动"
                ],
                "summary": "新增活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "versionNum",
                        "name": "versionNum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "content",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "level",
                        "name": "level",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "todoNum",
                        "name": "todoNum",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-event-delete": {
            "post": {
                "description": "删除版本活动",
                "tags": [
                    "版本活动"
                ],
                "summary": "删除版本活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-event-with-tag": {
            "get": {
                "description": "获取版本活动和tag",
                "tags": [
                    "版本活动w"
                ],
                "summary": "根据版本获取版本活动和tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "version_num",
                        "name": "versionId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建版本活动与Tag",
                "tags": [
                    "版本活动"
                ],
                "summary": "创建版本活动与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "versionEventId",
                        "name": "versionEventId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-event-with-tag-delete": {
            "post": {
                "description": "删除版本活动与Tag",
                "tags": [
                    "版本活动"
                ],
                "summary": "删除版本活动与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "versionEventId",
                        "name": "versionEventId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-tag": {
            "get": {
                "description": "获取Tag",
                "tags": [
                    "版本"
                ],
                "summary": "版本Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建版本与Tag",
                "tags": [
                    "版本"
                ],
                "summary": "创建版本与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "versionId",
                        "name": "versionId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-tag-delete": {
            "post": {
                "description": "删除版本与Tag",
                "tags": [
                    "版本"
                ],
                "summary": "删除版本和版本与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tagId",
                        "name": "tagId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "versionId",
                        "name": "versionId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version-with-tag": {
            "get": {
                "description": "获取版本与Tag",
                "tags": [
                    "版本"
                ],
                "summary": "版本和版本与Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请输入当前页，默认第一页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/versionEvent-tag": {
            "get": {
                "description": "获取Tag",
                "tags": [
                    "版本活动"
                ],
                "summary": "版本Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
