info:
  contact: {}
paths:
  /ping:
    get:
      description: ping
      responses:
        "200":
          description: '{"code":"200","data":"pong"}'
          schema:
            type: string
      summary: ping
      tags:
      - 测试
  /version:
    get:
      description: 获取版本列表
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 版本
      tags:
      - 版本
    post:
      description: 新增版本信息
      parameters:
      - description: num
        in: formData
        name: num
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: title
        in: formData
        name: title
        type: string
      - description: Img
        in: formData
        name: img
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 新增版本信息
      tags:
      - 版本
    put:
      description: 更新版本信息
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: num
        in: formData
        name: num
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: title
        in: formData
        name: title
        type: string
      - description: Img
        in: formData
        name: img
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 更新版本信息
      tags:
      - 版本
  /version-delete:
    post:
      description: 删除版本
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本
      tags:
      - 版本
  /version-event:
    get:
      description: 获取版本活动
      parameters:
      - description: version_num
        in: query
        name: version_num
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 根据版本获取版本活动
      tags:
      - 版本活动
    post:
      description: 新增版本活动
      parameters:
      - description: versionNum
        in: formData
        name: versionNum
        type: integer
      - description: title
        in: formData
        name: title
        type: string
      - description: content
        in: formData
        name: content
        type: string
      - description: level
        in: formData
        name: level
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: todoNum
        in: formData
        name: todoNum
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 新增版本活动
      tags:
      - 版本活动
    put:
      description: 修改版本活动
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: versionNum
        in: formData
        name: versionNum
        type: integer
      - description: title
        in: formData
        name: title
        type: string
      - description: content
        in: formData
        name: content
        type: string
      - description: level
        in: formData
        name: level
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: todoNum
        in: formData
        name: todoNum
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 修改版本活动
      tags:
      - 版本活动
  /version-event-delete:
    post:
      description: 删除版本活动
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本活动
      tags:
      - 版本活动
  /version-event-with-tag:
    get:
      description: 获取版本活动和tag
      parameters:
      - description: version_num
        in: query
        name: version_num
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 根据版本获取版本活动和tag
      tags:
      - 版本活动
  /version-event-with-tag-delete:
    post:
      description: 删除版本活动与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: versionEventId
        in: query
        name: versionEventId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本活动与Tag
      tags:
      - 版本活动
  /version-with-tag:
    get:
      description: 获取版本与Tag
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 版本和版本与Tag
      tags:
      - 版本
  /version-with-tag-delete:
    post:
      description: 删除版本与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: versionId
        in: query
        name: versionId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本和版本与Tag
      tags:
      - 版本
swagger: "2.0"
