info:
  contact: {}
paths:
  /event:
    get:
      description: 获取活动列表
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 活动
      tags:
      - 活动
    post:
      description: 新增活动信息
      parameters:
      - description: title
        in: formData
        name: title
        type: string
      - description: primogems
        in: formData
        name: primogems
        type: integer
      - description: award
        in: formData
        name: award
        type: string
      - description: preTask
        in: formData
        name: preTask
        type: integer
      - description: coPlay
        in: formData
        name: coPlay
        type: integer
      - description: todoNum
        in: formData
        name: todoNum
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 新增活动信息
      tags:
      - 活动
    put:
      description: 更新活动信息
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: title
        in: formData
        name: title
        type: string
      - description: primogems
        in: formData
        name: primogems
        type: integer
      - description: award
        in: formData
        name: award
        type: string
      - description: preTask
        in: formData
        name: preTask
        type: integer
      - description: coPlay
        in: formData
        name: coPlay
        type: integer
      - description: todoNum
        in: formData
        name: todoNum
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 更新活动信息
      tags:
      - 活动
  /event-delete:
    post:
      description: 删除活动
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除活动
      tags:
      - 活动
  /event-with-tag:
    get:
      description: 获取活动与Tag
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 活动和活动与Tag
      tags:
      - 活动
    post:
      description: 创建活动与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: EventId
        in: query
        name: eventId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 创建活动与Tag
      tags:
      - 活动
  /event-with-tag-delete:
    post:
      description: 删除活动与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: eventId
        in: query
        name: eventId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除活动和活动与Tag
      tags:
      - 活动
  /login:
    post:
      description: 登录
      parameters:
      - description: name
        in: formData
        name: name
        type: string
      - description: name
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 登录
      tags:
      - 用户
  /ping:
    get:
      description: ping
      responses:
        "200":
          description: '{"code":"200","data":"pong"}'
          schema:
            type: string
      summary: ping
      tags:
      - 测试
  /register:
    post:
      description: 注册
      parameters:
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 注册
      tags:
      - 用户
  /user:
    get:
      description: 获取用户列表
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户
    post:
      description: 新增用户信息
      parameters:
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: token
        in: formData
        name: token
        type: string
      - description: role
        in: formData
        name: role
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 新增用户信息
      tags:
      - 用户
    put:
      description: 修改用户信息
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: name
        in: formData
        name: name
        type: string
      - description: token
        in: formData
        name: token
        type: string
      - description: role
        in: formData
        name: role
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 修改用户信息
      tags:
      - 用户
  /user-delete:
    post:
      description: 删除用户
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
  /version:
    get:
      description: 获取版本列表
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 版本
      tags:
      - 版本
    post:
      description: 新增版本信息
      parameters:
      - description: num
        in: formData
        name: num
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: title
        in: formData
        name: title
        type: string
      - description: Img
        in: formData
        name: img
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 新增版本信息
      tags:
      - 版本
    put:
      description: 更新版本信息
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: num
        in: formData
        name: num
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: title
        in: formData
        name: title
        type: string
      - description: Img
        in: formData
        name: img
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 更新版本信息
      tags:
      - 版本
  /version-delete:
    post:
      description: 删除版本
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本
      tags:
      - 版本
  /version-event:
    get:
      description: 获取版本活动
      parameters:
      - description: version_num
        in: query
        name: version_num
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 根据版本获取版本活动
      tags:
      - 版本活动
    post:
      description: 新增活动
      parameters:
      - description: versionNum
        in: formData
        name: versionNum
        type: integer
      - description: title
        in: formData
        name: title
        type: string
      - description: content
        in: formData
        name: content
        type: string
      - description: level
        in: formData
        name: level
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: todoNum
        in: formData
        name: todoNum
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 新增活动
      tags:
      - 版本活动
    put:
      description: 修改版本活动
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: versionNum
        in: formData
        name: versionNum
        type: integer
      - description: title
        in: formData
        name: title
        type: string
      - description: content
        in: formData
        name: content
        type: string
      - description: level
        in: formData
        name: level
        type: integer
      - description: startTime
        in: formData
        name: startTime
        type: string
      - description: endTime
        in: formData
        name: endTime
        type: string
      - description: todoNum
        in: formData
        name: todoNum
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 修改版本活动
      tags:
      - 版本活动
  /version-event-delete:
    post:
      description: 删除版本活动
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本活动
      tags:
      - 版本活动
  /version-event-with-tag:
    get:
      description: 获取版本活动和tag
      parameters:
      - description: version_num
        in: query
        name: version_num
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 根据版本获取版本活动和tag
      tags:
      - 版本活动
    post:
      description: 创建版本活动与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: versionEventId
        in: query
        name: versionEventId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 创建版本活动与Tag
      tags:
      - 版本活动
  /version-event-with-tag-delete:
    post:
      description: 删除版本活动与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: versionEventId
        in: query
        name: versionEventId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本活动与Tag
      tags:
      - 版本活动
  /version-with-tag:
    get:
      description: 获取版本与Tag
      parameters:
      - description: 请输入当前页，默认第一页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 版本和版本与Tag
      tags:
      - 版本
    post:
      description: 创建版本与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: versionId
        in: query
        name: versionId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 创建版本与Tag
      tags:
      - 版本
  /version-with-tag-delete:
    post:
      description: 删除版本与Tag
      parameters:
      - description: tagId
        in: query
        name: tagId
        type: integer
      - description: versionId
        in: query
        name: versionId
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":"","data":""}'
          schema:
            type: string
      summary: 删除版本和版本与Tag
      tags:
      - 版本
swagger: "2.0"
