info:
  contact: {}
paths:
  /ping:
    get:
      description: ping
      responses:
        "200":
          description: '{"code":"200","data":"pong"}'
          schema:
            type: string
      summary: ping
      tags:
      - 测试
swagger: "2.0"
